version: 1.0.{build}
os: WMF 5
build: false

skip_commits:
  files:
    - README.md
  message: /updated readme.*|update readme.*s|update docs.*|update version.*|update appveyor.*/

install:
  - ps: Install-PackageProvider -Name NuGet -Force
  - ps: Install-Module PsScriptAnalyzer -Force
  - ps: Install-Module Pester -Force
  - ps: Install-Module AzureRM.KeyVault -Force

build_script: 
  - ps: . .\appveyor\build.ps1

test_script: 
  - ps: . .\appveyor\test.ps1

