version: 1.1.{build}
os: WMF 5
build: false

environment:
  psgallery_api_key:
    secure: K9XoMzIw8isRMSZB5zd2IPaB8V6IkWElN04L7EFAes7mZ1TWuQsJthDcumV6/qAd

skip_commits:
  files:
    - README.md
  message: /updated readme.*|update readme.*s|update docs.*|update version.*|update appveyor.*/

install:
  - ps: Install-PackageProvider -Name NuGet -Force
  - ps: Install-Module PsScriptAnalyzer -Force
  - ps: Install-Module Pester -Force
  - ps: Install-Module AzureRM.KeyVault -Force

build_script: 
  - ps: . .\appveyor\build.ps1

test_script: 
  - ps: . .\appveyor\test.ps1

deploy_script:
  - ps: . .\appveyor\deploy.ps1